"""Port (Protocol) for clip candidate/selection persistence."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from cliptrans.domain.models import ClipCandidate, ClipSelection


class ClipRepositoryPort(Protocol):
    async def save_candidate(self, candidate: ClipCandidate) -> None: ...
    async def save_candidates(self, candidates: list[ClipCandidate]) -> None: ...
    async def get_candidates(self, stream_id: str) -> list[ClipCandidate]: ...
    async def get_candidate(self, candidate_id: UUID) -> ClipCandidate | None: ...
    async def delete_candidates(self, stream_id: str) -> None: ...

    async def save_selection(self, selection: ClipSelection) -> None: ...
    async def get_selections(
        self, *, stream_id: str | None = None, status: str | None = None
    ) -> list[ClipSelection]: ...
    async def get_selection(self, selection_id: UUID) -> ClipSelection | None: ...
    async def update_selection(self, selection: ClipSelection) -> None: ...
    async def delete_selection(self, selection_id: UUID) -> None: ...
